document.getElementById("login_form").addEventListener("submit", async (event) => {//מחכה לשליחת טופס ההתחברות על ידי המשתמש
    event.preventDefault();
    const form = document.getElementById("login_form");//get the form element
    const formData = new FormData(form);
    const formDataObject = {};
    formData.forEach((value, key) => {
      formDataObject[key] = value;
    });//run on each value from the form Data. key=input name, value=user's value on specific input box
    const formDataJson = JSON.stringify(formDataObject);//המרת המילון שהכיל את תוכן הטופס לקובץ מסוג ג'יסון
    const response = await fetch("http://localhost:8080/login_form", {//sending the login form to Node JS Server 
      method: "POST",
      credentials: "same-origin",
      headers: {
        "Content-Type": "application/json", // Set the content type to JSON
      },
      body: formDataJson,
    });
    const data = await response.json();//the respone that was recived from the Node JS Server
    if (data.status == "failed"){//if the respone meassage has status "failed" (status types are generated by the server)
      document.getElementById("message").innerHTML = "Email Address And/Or Password are incorrect";//הצגת הודעת שגיאה למשתמש
    }
    else if (data.status == "success") {//if the respone message has status "success"
      if (document.getElementById("remember-me").checked) {//בדיקה האם שדה "תזכור אותי" סומן על ידי המשתמש
        setCookie("userId", data.uid, 2);//saving userId in Cookie for 2 days
        setCookie("username", data.user.username, 2);//saving username in Cookie for 2 days
      } else {//אם שדה "זכור אותי" לא סומן על ידי המשתמש
        setCookie("userId", data.uid, 0.041);//saving userId in Cookie for one hour
        setCookie("username", data.user.username, 0.041);//saving username in Cookie for one hour
      }
      location.href = "index.html";//go to the home page
    }
  });
